#!/usr/bin/with-contenv bashio
# shellcheck shell=bash
set -euo pipefail

## Make the kernel's nfsd control filesystem available at /proc/fs/nfsd.
##
## /proc/fs/nfsd is just an (empty) mountpoint which the kernel provides in
## every procfs instance; the actual control files (e.g. `versions`, `threads`)
## only exist once the `nfsd` filesystem is mounted there. Mounting it also
## autoloads the `nfsd` kernel module on hosts that ship it (Home Assistant OS
## provides the module on some boards, e.g. Rockchip-based ones like the
## ODROID-M1). For hosts without module autoload, we try to load the module
## explicitly first (host kernel modules are mapped into the app read-only).
if [ ! -e /proc/fs/nfsd/versions ]; then
  if command -v modprobe >/dev/null 2>&1; then
    bashio::log.info "Loading nfsd kernel module (if available)..."
    modprobe nfsd 2>/dev/null || true
  fi
  bashio::log.info "Mounting nfsd filesystem..."
  if ! mount -t nfsd nfsd /proc/fs/nfsd; then
    bashio::log.fatal "Unable to mount the nfsd filesystem: the host's kernel probably lacks NFS server support."
    bashio::log.fatal "Note: Home Assistant OS only ships the nfsd kernel module on some boards"
    bashio::log.fatal "(currently the Rockchip-based ones, e.g. ODROID-M1/M1S and Home Assistant Green)."
    bashio::exit.nok
  fi
fi

## NOTE: We deliberately do NOT disable NFSv2/v3 via
## /proc/fs/nfsd/versions here: rpc.nfsd configures the kernel's version set
## itself (see /etc/s6-overlay/scripts/nfsd-start), and the shell's echo/
## printf builtins in this image issue writev(2) (text and trailing newline
## as separate iovecs), which the kernel's nfsd control files - old-style
## .write only, no .write_iter - reject with EINVAL.

## Validate each share configuration and generate /etc/exports from it
bashio::log.info "Configuring NFS shares..."
echo "# Generated by Home Assistant NFS Server app" >/etc/exports

## Get user configuration values
DEFAULT_UID=$(bashio::config 'default_uid')
DEFAULT_GID=$(bashio::config 'default_gid')
DEFAULT_PERMS=$(bashio::config 'default_permissions')
SHARES=$(bashio::config 'shares')
if bashio::var.is_empty "${SHARES}"; then
  bashio::exit.nok "No NFS shares configured. Please add shares in the app's configuration."
fi

## Process each share configuration
while IFS= read -r share; do
  path=$(bashio::jq "$share" '.path')
  network=$(bashio::jq "$share" '.network')
  options=$(bashio::jq "$share" '.options')

  bashio::log.info "Exporting NFS share ${path} for ${network} with options ${options}"

  ## Only directories mapped into the app can be exported: unmapped paths
  ## would either be created in the app's ephemeral filesystem (losing all
  ## data on restart) or are plain unusable for clients.
  if [[ "${path}" != /share && "${path}" != /share/* &&
    "${path}" != /media && "${path}" != /media/* ]]; then
    bashio::log.fatal "Share path ${path} is outside of /share/ or /media/: only directories mapped into the app can be exported."
    bashio::exit.nok
  fi

  echo "${path} ${network}(${options})" >>/etc/exports

  # Create share directory if it doesn't exist, but don't modify existing ones
  if [ ! -d "${path}" ]; then
    bashio::log.info "Creating directory ${path} for NFS share"
    mkdir -p "${path}"
    # Set permissions using configured defaults
    chmod "${DEFAULT_PERMS}" "${path}"
    chown "${DEFAULT_UID}:${DEFAULT_GID}" "${path}"
    bashio::log.info "Created ${path} with UID:${DEFAULT_UID} GID:${DEFAULT_GID} Permissions:${DEFAULT_PERMS}"
  else
    current_perms=$(ls -ld "${path}")
    bashio::log.info "Using existing directory ${path} for NFS share"
    bashio::log.info "Current permissions and ownership for ${path}: $(echo "${current_perms}" | awk '{print $1 " " $3 ":" $4}')"
  fi
done < <(echo "${SHARES}")

bashio::log.info "Configuring NFS shares completed"
