#!/usr/bin/with-contenv bashio
# shellcheck shell=bash
set -euo pipefail

bashio::log.info "Disabling NFSv2 and NFSv3 support at kernel level..."
echo "-2 -3" >/proc/fs/nfsd/versions
bashio::log.info "Enabled NFS versions: $(cat /proc/fs/nfsd/versions | grep -o '+[0-9.]*' | sed 's/^+/v/' | paste -sd ', ' -)"

# Generate /etc/exports from config
bashio::log.info "Configuring NFS shares..."
echo "# Generated by Home Assistant NFS Server app" >/etc/exports

## Get user configuration values
DEFAULT_UID=$(bashio::config 'default_uid')
DEFAULT_GID=$(bashio::config 'default_gid')
DEFAULT_PERMS=$(bashio::config 'default_permissions')
SHARES=$(bashio::config 'shares')
if bashio::var.is_empty "${SHARES}"; then
  bashio::exit.nok "No NFS shares configured. Please add shares in the app's configuration."
fi

## Define function to check if share is read-write (last option wins)
is_rw_share() {
  local options="$1"
  local last_rw_ro=""

  # Split options by comma and find the last rw/ro option
  IFS=',' read -ra opts <<<"$options"
  for opt in "${opts[@]}"; do
    opt=$(echo "$opt" | xargs) # Trim whitespace
    case "$opt" in
      rw | ro)
        last_rw_ro="$opt"
        ;;
    esac
  done

  # If no rw/ro option found, default to read-only
  if [ -z "$last_rw_ro" ] || [ "$last_rw_ro" = "ro" ]; then
    return 1 # RO share
  else
    return 0 # RW share
  fi
}

## Process each share configuration
while IFS= read -r share; do
  path=$(bashio::jq "$share" '.path')
  network=$(bashio::jq "$share" '.network')
  options=$(bashio::jq "$share" '.options')
  
  bashio::log.info "Exporting NFS share ${path} for ${network} with options ${options}"
  echo "${path} ${network}(${options})" >>/etc/exports

  # Create share directory if it doesn't exist, but don't modify existing ones
  if [ ! -d "${path}" ]; then
    bashio::log.info "Creating directory ${path} for NFS share"
    mkdir -p "${path}"
    # Set permissions using configured defaults
    chmod "${DEFAULT_PERMS}" "${path}"
    chown "${DEFAULT_UID}:${DEFAULT_GID}" "${path}"
    bashio::log.info "Created ${path} with UID:${DEFAULT_UID} GID:${DEFAULT_GID} Permissions:${DEFAULT_PERMS}"
  else
    current_perms=$(ls -ld "${path}")
    bashio::log.info "Using existing directory ${path} for NFS share"
    bashio::log.info "Current permissions and ownership for ${path}: $(echo "${current_perms}" | awk '{print $1 " " $3 ":" $4}')"

    # Check basic required permissions (read + execute for directory traversal)
    if [ ! -r "${path}" ]; then
      bashio::log.error "Directory ${path} is not readable by the NFS server."
      bashio::log.error "NFS server needs read permission to serve this directory."
    fi

    if [ ! -x "${path}" ]; then
      bashio::log.error "Directory ${path} is not searchable by the NFS server."
      bashio::log.error "NFS server needs execute permission to traverse this directory."
    fi

    # Check write permissions for read-write shares
    if is_rw_share "${options}" && [ ! -w "${path}" ]; then
      bashio::log.error "Directory ${path} is not writable by the NFS server."
      bashio::log.error "Share is configured as read-write but directory lacks write permission."
      bashio::log.error "Either make directory writable or change share options to 'ro'."
    fi
  fi
done < <(echo "${SHARES}")

bashio::log.info "Configuring NFS shares completed"
