#!/usr/bin/with-contenv bashio
# shellcheck shell=bash
set -euo pipefail

## Make the kernel's nfsd control filesystem available at /proc/fs/nfsd.
##
## /proc/fs/nfsd is just an (empty) mountpoint which the kernel provides in
## every procfs instance; the actual control files (e.g. `versions`, `threads`)
## only exist once the `nfsd` filesystem is mounted there. Mounting it also
## autoloads the `nfsd` kernel module on hosts that ship it (Home Assistant OS
## provides the module on some boards, e.g. Rockchip-based ones like the
## ODROID-M1). For hosts without module autoload, we try to load the module
## explicitly first (host kernel modules are mapped into the app read-only).
if [ ! -e /proc/fs/nfsd/versions ]; then
  if command -v modprobe >/dev/null 2>&1; then
    bashio::log.info "Loading nfsd kernel module (if available)..."
    modprobe nfsd 2>/dev/null || true
  fi
  bashio::log.info "Mounting nfsd filesystem..."
  if ! mount -t nfsd nfsd /proc/fs/nfsd; then
    bashio::log.fatal "Unable to mount the nfsd filesystem: the host's kernel probably lacks NFS server support."
    bashio::log.fatal "Note: Home Assistant OS only ships the nfsd kernel module on some boards"
    bashio::log.fatal "(currently the Rockchip-based ones, e.g. ODROID-M1/M1S and Home Assistant Green)."
    bashio::exit.nok
  fi
fi

## Make sure only NFSv4 is offered at kernel level.
##
## NOTE: NFSv2 server support is not compiled into current kernels anymore
## (CONFIG_NFSD_V2 defaults to off), hence we only disable versions that the
## kernel actually offers: kernels may reject version writes that reference
## non-available versions with EINVAL instead of ignoring them.
NFS_VERSIONS="$(</proc/fs/nfsd/versions)"
DISABLE_VERSIONS="-3"
if grep -q '+2' <<<"${NFS_VERSIONS}"; then
  DISABLE_VERSIONS="-2 ${DISABLE_VERSIONS}"
fi
bashio::log.info "Disabling kernel-level NFS versions: ${DISABLE_VERSIONS}"
if ! echo "${DISABLE_VERSIONS}" >/proc/fs/nfsd/versions; then
  bashio::log.warning "Unable to set NFS versions at kernel level (is nfsd already running?)"
fi
NFS_VERSIONS="$(</proc/fs/nfsd/versions)"
bashio::log.info "Enabled NFS versions: ${NFS_VERSIONS}"
if grep -qE '\+(2|3)( |$)' <<<"${NFS_VERSIONS}"; then
  bashio::log.warning "NFSv2 or NFSv3 is still enabled at kernel level despite the request to disable it."
fi

# Generate /etc/exports from config
bashio::log.info "Configuring NFS shares..."
echo "# Generated by Home Assistant NFS Server app" >/etc/exports

## Get user configuration values
DEFAULT_UID=$(bashio::config 'default_uid')
DEFAULT_GID=$(bashio::config 'default_gid')
DEFAULT_PERMS=$(bashio::config 'default_permissions')
SHARES=$(bashio::config 'shares')
if bashio::var.is_empty "${SHARES}"; then
  bashio::exit.nok "No NFS shares configured. Please add shares in the app's configuration."
fi

## Define function to check if share is read-write (last option wins)
is_rw_share() {
  local options="$1"
  local last_rw_ro=""

  # Split options by comma and find the last rw/ro option
  IFS=',' read -ra opts <<<"$options"
  for opt in "${opts[@]}"; do
    opt=$(echo "$opt" | xargs) # Trim whitespace
    case "$opt" in
      rw | ro)
        last_rw_ro="$opt"
        ;;
    esac
  done

  # If no rw/ro option found, default to read-only
  if [ -z "$last_rw_ro" ] || [ "$last_rw_ro" = "ro" ]; then
    return 1 # RO share
  else
    return 0 # RW share
  fi
}

## Process each share configuration
while IFS= read -r share; do
  path=$(bashio::jq "$share" '.path')
  network=$(bashio::jq "$share" '.network')
  options=$(bashio::jq "$share" '.options')

  bashio::log.info "Exporting NFS share ${path} for ${network} with options ${options}"
  echo "${path} ${network}(${options})" >>/etc/exports

  # Create share directory if it doesn't exist, but don't modify existing ones
  if [ ! -d "${path}" ]; then
    bashio::log.info "Creating directory ${path} for NFS share"
    mkdir -p "${path}"
    # Set permissions using configured defaults
    chmod "${DEFAULT_PERMS}" "${path}"
    chown "${DEFAULT_UID}:${DEFAULT_GID}" "${path}"
    bashio::log.info "Created ${path} with UID:${DEFAULT_UID} GID:${DEFAULT_GID} Permissions:${DEFAULT_PERMS}"
  else
    current_perms=$(ls -ld "${path}")
    bashio::log.info "Using existing directory ${path} for NFS share"
    bashio::log.info "Current permissions and ownership for ${path}: $(echo "${current_perms}" | awk '{print $1 " " $3 ":" $4}')"

    # Check basic required permissions (read + execute for directory traversal)
    if [ ! -r "${path}" ]; then
      bashio::log.error "Directory ${path} is not readable by the NFS server."
      bashio::log.error "NFS server needs read permission to serve this directory."
    fi

    if [ ! -x "${path}" ]; then
      bashio::log.error "Directory ${path} is not searchable by the NFS server."
      bashio::log.error "NFS server needs execute permission to traverse this directory."
    fi

    # Check write permissions for read-write shares
    if is_rw_share "${options}" && [ ! -w "${path}" ]; then
      bashio::log.error "Directory ${path} is not writable by the NFS server."
      bashio::log.error "Share is configured as read-write but directory lacks write permission."
      bashio::log.error "Either make directory writable or change share options to 'ro'."
    fi
  fi
done < <(echo "${SHARES}")

bashio::log.info "Configuring NFS shares completed"
